# Makes artifactory the default registry and saves passing --registry parameter
[registry]
default = "artifactory"

[registries.artifactory]
index = "sparse+https://192.168.0.11/artifactory/api/cargo/index.crates.io/index/"

# Add these 2 sections for resolving dependencies from Artifactory
[source.artifactory-remote]
registry = "sparse+https://192.168.0.11/artifactory/api/cargo/index.crates.io/index/"

[source.crates-io]
replace-with = "artifactory-remote"

[http]
debug = true
#cainfo = "/etc/pki/tls/certs/artifactory.crt"
